import { mkdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'

import {
  ContractFailure,
  contractPaths,
  invariant,
  sha256,
  stableJson,
} from './context.mjs'
import { resolveLocalReference } from './openapi.mjs'

const GENERATOR_VERSION = 'poolai-contracts/1.0.0'

const CSHARP_JSON_ELEMENT_ALLOWLIST = new Set([
  '#/components/schemas/ChatAssistantMessage/properties/content',
  '#/components/schemas/ChatCompletionRequest/properties/tool_choice',
  '#/components/schemas/ChatDeveloperMessage/properties/content',
  '#/components/schemas/ChatSystemMessage/properties/content',
  '#/components/schemas/ChatToolMessage/properties/content',
  '#/components/schemas/ChatUserMessage/properties/content',
  '#/components/schemas/OpenAIResponse/properties/output/items',
  '#/components/schemas/OpenAIResponse/properties/tool_choice',
  '#/components/schemas/ResponseCreateRequest/properties/input',
  '#/components/schemas/ResponseCreateRequest/properties/tool_choice',
  '#/components/schemas/ResponseInputMessage/properties/content',
])

const CSHARP_ROOT_JSON_ELEMENT_ALLOWLIST = new Set(['ChatMessage', 'LoginResult'])

function generatedHeader(comment, openApiSource, errorCatalogSource) {
  return [
    `${comment} <auto-generated>`,
    `${comment} Generator: ${GENERATOR_VERSION}`,
    `${comment} SHA-256(openapi-v1.yaml) ${sha256(openApiSource)}`,
    `${comment} SHA-256(error-catalog.md) ${sha256(errorCatalogSource)}`,
    `${comment} Sources: docs/contracts/openapi-v1.yaml, docs/contracts/error-catalog.md`,
    `${comment} Do not edit this file by hand.`,
    `${comment} </auto-generated>`,
    '',
  ].join('\n')
}

function literal(value) {
  if (typeof value === 'string') {
    return JSON.stringify(value)
  }
  if (value === null || typeof value === 'number' || typeof value === 'boolean') {
    return String(value)
  }
  throw new ContractFailure(`Unsupported enum/const literal: ${stableJson(value)}`)
}

function isNullable(schema) {
  if (schema?.type === 'null') {
    return true
  }
  if (Array.isArray(schema?.type) && schema.type.includes('null')) {
    return true
  }
  return [...(schema?.oneOf ?? []), ...(schema?.anyOf ?? [])].some(
    (candidate) => candidate?.type === 'null',
  )
}

function withoutNull(schema) {
  if (!schema || typeof schema !== 'object') {
    return schema
  }
  if (Array.isArray(schema.type)) {
    const types = schema.type.filter((type) => type !== 'null')
    return { ...schema, type: types.length === 1 ? types[0] : types }
  }
  for (const keyword of ['oneOf', 'anyOf']) {
    if (schema[keyword]) {
      const options = schema[keyword].filter((candidate) => candidate?.type !== 'null')
      if (options.length === 1 && Object.keys(schema).every((key) => [keyword, 'description'].includes(key))) {
        return options[0]
      }
      return { ...schema, [keyword]: options }
    }
  }
  return schema
}

function tsPropertyName(name) {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/u.test(name) ? name : JSON.stringify(name)
}

function tsObject(schema, context, depth) {
  const required = new Set(schema.required ?? [])
  const indent = '  '.repeat(depth)
  const childIndent = '  '.repeat(depth + 1)
  const properties = Object.entries(schema.properties ?? {}).map(([name, child]) => {
    const optional = required.has(name) ? '' : '?'
    return `${childIndent}${tsPropertyName(name)}${optional}: ${tsType(child, `${context}/properties/${name}`, depth + 1)}`
  })

  if (schema.additionalProperties && typeof schema.additionalProperties === 'object') {
    properties.push(
      `${childIndent}[key: string]: ${tsType(schema.additionalProperties, `${context}/additionalProperties`, depth + 1)}`,
    )
  } else if (schema.additionalProperties === true) {
    properties.push(`${childIndent}[key: string]: JsonValue`)
  }

  if (properties.length === 0) {
    return schema.additionalProperties === false ? 'Record<string, never>' : 'Record<string, JsonValue>'
  }
  return `{\n${properties.join('\n')}\n${indent}}`
}

function hasRepresentableTypeShape(schema) {
  return Boolean(
    schema?.$ref ||
      schema?.type ||
      schema?.properties ||
      schema?.const !== undefined ||
      schema?.enum ||
      schema?.oneOf?.some(hasRepresentableTypeShape) ||
      schema?.anyOf?.some(hasRepresentableTypeShape) ||
      schema?.allOf?.some(hasRepresentableTypeShape),
  )
}

function tsType(schema, context, depth = 0) {
  if (schema === true) {
    return 'JsonValue'
  }
  if (schema === false) {
    return 'never'
  }
  invariant(schema && typeof schema === 'object', `Invalid schema at ${context}.`)
  if (schema.$ref) {
    return schema.$ref.split('/').at(-1)
  }
  if ('const' in schema) {
    return literal(schema.const)
  }
  if (schema.enum) {
    return schema.enum.map(literal).join(' | ')
  }

  if (Array.isArray(schema.type)) {
    return schema.type
      .map((type) => tsType({ ...schema, type }, context, depth))
      .filter((type, index, all) => all.indexOf(type) === index)
      .join(' | ')
  }

  const hasObjectShape = schema.type === 'object' || schema.properties
  if (hasObjectShape) {
    let result = tsObject(schema, context, depth)
    if (schema.allOf) {
      const representedParts = schema.allOf
        .map((part, index) => ({ index, part }))
        .filter(({ part }) => hasRepresentableTypeShape(part))
        .map(({ index, part }) => tsType(part, `${context}/allOf/${index}`, depth))
      result = [result, ...representedParts].join(' & ')
    }
    return result
  }

  if (schema.allOf) {
    return schema.allOf
      .map((part, index) => tsType(part, `${context}/allOf/${index}`, depth))
      .join(' & ')
  }
  for (const keyword of ['oneOf', 'anyOf']) {
    if (schema[keyword]) {
      return schema[keyword]
        .map((part, index) => tsType(part, `${context}/${keyword}/${index}`, depth))
        .filter((type, index, all) => all.indexOf(type) === index)
        .join(' | ')
    }
  }

  switch (schema.type) {
    case 'array':
      return `ReadonlyArray<${tsType(schema.items ?? true, `${context}/items`, depth)}>`
    case 'boolean':
      return 'boolean'
    case 'integer':
    case 'number':
      return 'number'
    case 'null':
      return 'null'
    case 'string':
      return 'string'
    case undefined:
      if (schema.if || schema.then) {
        return 'JsonValue'
      }
      throw new ContractFailure(`Schema at ${context} has no supported type form.`)
    default:
      throw new ContractFailure(`Unsupported TypeScript schema type ${schema.type} at ${context}.`)
  }
}

function operationMetadata(openApi) {
  const methods = ['get', 'put', 'post', 'delete', 'options', 'head', 'patch', 'trace']
  const entries = []
  for (const [route, pathItem] of Object.entries(openApi.paths)) {
    for (const method of methods) {
      const operation = pathItem[method]
      if (!operation) {
        continue
      }
      entries.push({
        id: operation.operationId,
        method: method.toUpperCase(),
        path: route,
        roles: operation['x-required-roles'] ?? [],
      })
    }
  }
  return entries.sort((left, right) => left.id.localeCompare(right.id))
}

export function generateTypeScript(openApi, openApiSource, errorCatalogSource) {
  const lines = [
    generatedHeader('//', openApiSource, errorCatalogSource).trimEnd(),
    'export type JsonPrimitive = boolean | number | string | null',
    'export type JsonValue = JsonPrimitive | ReadonlyArray<JsonValue> | { readonly [key: string]: JsonValue }',
    '',
  ]

  for (const [name, schema] of Object.entries(openApi.components.schemas).sort(([left], [right]) =>
    left.localeCompare(right),
  )) {
    lines.push(
      `export type ${name} = ${tsType(schema, `#/components/schemas/${name}`)}`,
      '',
    )
  }

  lines.push('export const openApiOperations = {')
  for (const operation of operationMetadata(openApi)) {
    lines.push(
      `  ${JSON.stringify(operation.id)}: { method: ${JSON.stringify(operation.method)}, path: ${JSON.stringify(operation.path)}, requiredRoles: ${JSON.stringify(operation.roles)} },`,
    )
  }
  lines.push('} as const', '', 'export type OpenApiOperationId = keyof typeof openApiOperations', '')
  return `${lines.join('\n')}\n`
}

function csharpIdentifier(value) {
  const words = value.split(/[^A-Za-z0-9]+/u).filter(Boolean)
  let identifier = words
    .map((word) => `${word[0]?.toUpperCase() ?? ''}${word.slice(1)}`)
    .join('')
  if (/^[0-9]/u.test(identifier)) {
    identifier = `Value${identifier}`
  }
  return identifier || 'Value'
}

function enumMembers(schema) {
  const used = new Set()
  return schema.enum.map((wireValue, index) => {
    invariant(typeof wireValue === 'string', 'C# generator supports only string root enums.')
    let name = csharpIdentifier(wireValue)
    if (used.has(name)) {
      name = `${name}${index + 1}`
    }
    used.add(name)
    return { name, wireValue }
  })
}

function csharpGenerator(openApi) {
  const componentSchemas = openApi.components.schemas
  const rootEnums = new Set(
    Object.entries(componentSchemas)
      .filter(([, schema]) => Array.isArray(schema.enum) && schema.enum.every((value) => typeof value === 'string'))
      .map(([name]) => name),
  )
  const classes = new Map()
  const classQueue = []

  function resolve(schema) {
    return schema?.$ref ? resolveLocalReference(openApi, schema.$ref) : schema
  }

  function objectLike(schema, stack = new Set()) {
    if (!schema || typeof schema !== 'object') {
      return false
    }
    if (schema.$ref) {
      if (stack.has(schema.$ref)) {
        return true
      }
      return objectLike(resolve(schema), new Set(stack).add(schema.$ref))
    }
    if (schema.type === 'object' || schema.properties) {
      return true
    }
    for (const keyword of ['allOf', 'oneOf', 'anyOf']) {
      if (schema[keyword]?.length && schema[keyword].every((candidate) => objectLike(candidate, stack))) {
        return true
      }
    }
    return false
  }

  function mergeShapes(shapes, union) {
    const result = { additionalProperties: false, properties: new Map(), required: new Set() }
    if (shapes.length === 0) {
      return result
    }
    const required = union
      ? shapes
          .map((shape) => shape.required)
          .reduce(
            (intersection, current) => new Set([...intersection].filter((name) => current.has(name))),
          )
      : new Set(shapes.flatMap((shape) => [...shape.required]))
    result.required = required
    result.additionalProperties = shapes.some((shape) => shape.additionalProperties)
    for (const shape of shapes) {
      for (const [name, schema] of shape.properties) {
        const existing = result.properties.get(name)
        if (!existing) {
          result.properties.set(name, schema)
        } else if (stableJson(existing) !== stableJson(schema)) {
          const refines = (candidate, base) =>
            candidate?.allOf?.some(
              (part) =>
                stableJson(part) === stableJson(base) ||
                (base?.$ref && part?.$ref === base.$ref),
            )
          if (refines(schema, existing)) {
            result.properties.set(name, schema)
          } else if (!refines(existing, schema)) {
            const options = [...(existing.anyOf ?? [existing]), ...(schema.anyOf ?? [schema])]
            const unique = [
              ...new Map(options.map((option) => [stableJson(option), option])).values(),
            ]
            result.properties.set(name, { anyOf: unique })
          }
        }
      }
    }
    return result
  }

  function collectShape(schema, referenceStack = new Set()) {
    if (schema.$ref) {
      invariant(!referenceStack.has(schema.$ref), `Recursive object inheritance at ${schema.$ref}.`)
      return collectShape(resolve(schema), new Set(referenceStack).add(schema.$ref))
    }
    const direct = {
      additionalProperties:
        schema.additionalProperties === true ||
        (schema.additionalProperties !== null && typeof schema.additionalProperties === 'object'),
      properties: new Map(Object.entries(schema.properties ?? {})),
      required: new Set(schema.required ?? []),
    }
    const intersections = (schema.allOf ?? []).map((part) => collectShape(part, referenceStack))
    let result = mergeShapes([direct, ...intersections], false)

    if (!schema.type && !schema.properties) {
      for (const keyword of ['oneOf', 'anyOf']) {
        if (schema[keyword]?.length && schema[keyword].every((part) => objectLike(part))) {
          result = mergeShapes(
            schema[keyword].map((part) => collectShape(part, referenceStack)),
            true,
          )
          break
        }
      }
    }
    return result
  }

  function reserveClass(preferredName, schema, pointer) {
    let name = csharpIdentifier(preferredName)
    let suffix = 2
    while (classes.has(name) && stableJson(classes.get(name).schema) !== stableJson(schema)) {
      name = `${csharpIdentifier(preferredName)}${suffix}`
      suffix += 1
    }
    if (!classes.has(name)) {
      const entry = { name, pointer, schema }
      classes.set(name, entry)
      classQueue.push(entry)
    }
    return name
  }

  function componentName(reference) {
    return reference.split('/').at(-1)
  }

  function nullable(type) {
    return type.text.endsWith('?') ? type : { ...type, text: `${type.text}?` }
  }

  function collapseNullableVariants(types) {
    const baseTypes = new Map()
    for (const type of types) {
      const baseText = type.text.endsWith('?') ? type.text.slice(0, -1) : type.text
      baseTypes.set(baseText, { ...type, text: baseText })
    }
    if (baseTypes.size !== 1) {
      return null
    }
    const result = [...baseTypes.values()][0]
    return types.some((type) => type.text.endsWith('?')) ? nullable(result) : result
  }

  function csharpType(schema, preferredName, pointer) {
    if (schema === true) {
      invariant(CSHARP_JSON_ELEMENT_ALLOWLIST.has(pointer), `Unapproved JsonElement fallback at ${pointer}.`)
      return { text: 'JsonElement', valueType: true }
    }
    invariant(schema && typeof schema === 'object', `Invalid C# schema at ${pointer}.`)
    const allowsNull = isNullable(schema)
    schema = withoutNull(schema)

    if (
      CSHARP_JSON_ELEMENT_ALLOWLIST.has(pointer) &&
      (schema.oneOf || schema.anyOf || Array.isArray(schema.type))
    ) {
      return allowsNull
        ? { text: 'JsonElement?', valueType: true }
        : { text: 'JsonElement', valueType: true }
    }

    if (schema.$ref) {
      const name = componentName(schema.$ref)
      let type
      if (CSHARP_ROOT_JSON_ELEMENT_ALLOWLIST.has(name)) {
        type = { text: 'JsonElement', valueType: true }
      } else if (rootEnums.has(name)) {
        type = { text: name, valueType: true }
      } else if (objectLike(schema)) {
        type = { text: name, valueType: false }
      } else {
        type = csharpType(resolve(schema), preferredName, pointer)
      }
      return allowsNull ? nullable(type) : type
    }

    if ('const' in schema || schema.enum) {
      const sample = 'const' in schema ? schema.const : schema.enum[0]
      const type =
        typeof sample === 'string'
          ? { text: 'string', valueType: false }
          : typeof sample === 'boolean'
            ? { text: 'bool', valueType: true }
            : { text: 'long', valueType: true }
      return allowsNull ? nullable(type) : type
    }

    if (Array.isArray(schema.type)) {
      const types = schema.type.map((type) => csharpType({ ...schema, type }, preferredName, pointer))
      const distinct = [...new Map(types.map((type) => [type.text, type])).values()]
      if (distinct.length === 1) {
        return allowsNull ? nullable(distinct[0]) : distinct[0]
      }
      invariant(CSHARP_JSON_ELEMENT_ALLOWLIST.has(pointer), `Unapproved mixed C# union at ${pointer}.`)
      return allowsNull
        ? { text: 'JsonElement?', valueType: true }
        : { text: 'JsonElement', valueType: true }
    }

    if (schema.type === 'object' || schema.properties || schema.allOf) {
      if (!schema.properties && !schema.allOf && schema.additionalProperties === true) {
        const type = { text: 'IReadOnlyDictionary<string, JsonElement>', valueType: false }
        return allowsNull ? nullable(type) : type
      }
      if (
        !schema.properties &&
        !schema.allOf &&
        schema.additionalProperties &&
        typeof schema.additionalProperties === 'object'
      ) {
        const valueType = csharpType(
          schema.additionalProperties,
          `${preferredName}Value`,
          `${pointer}/additionalProperties`,
        )
        const type = {
          text: `IReadOnlyDictionary<string, ${valueType.text}>`,
          valueType: false,
        }
        return allowsNull ? nullable(type) : type
      }
      const name = reserveClass(preferredName, schema, pointer)
      const type = { text: name, valueType: false }
      return allowsNull ? nullable(type) : type
    }

    for (const keyword of ['oneOf', 'anyOf']) {
      if (schema[keyword]) {
        const candidates = schema[keyword]
        if (candidates.every((candidate) => objectLike(candidate))) {
          throw new ContractFailure(
            `Unapproved object union at ${pointer}; use a converter or add an explicit JsonElement allowlist entry.`,
          )
        }
        const candidateTypes = candidates.map((candidate) =>
          csharpType(candidate, preferredName, pointer),
        )
        const distinct = [...new Map(candidateTypes.map((type) => [type.text, type])).values()]
        if (distinct.length === 1) {
          return allowsNull ? nullable(distinct[0]) : distinct[0]
        }
        const collapsed = collapseNullableVariants(distinct)
        if (collapsed) {
          return allowsNull ? nullable(collapsed) : collapsed
        }
        invariant(CSHARP_JSON_ELEMENT_ALLOWLIST.has(pointer), `Unapproved mixed C# union at ${pointer}.`)
        return allowsNull
          ? { text: 'JsonElement?', valueType: true }
          : { text: 'JsonElement', valueType: true }
      }
    }

    let type
    switch (schema.type) {
      case 'array': {
        const item = csharpType(schema.items ?? true, `${preferredName}Item`, `${pointer}/items`)
        type = { text: `IReadOnlyList<${item.text}>`, valueType: false }
        break
      }
      case 'boolean':
        type = { text: 'bool', valueType: true }
        break
      case 'integer':
        type = { text: schema.format === 'int32' ? 'int' : 'long', valueType: true }
        break
      case 'number':
        type = { text: schema.format === 'double' ? 'double' : 'decimal', valueType: true }
        break
      case 'null':
        type = { text: 'object?', valueType: false }
        break
      case 'string':
        if (schema.format === 'uuid') {
          type = { text: 'Guid', valueType: true }
        } else if (schema.format === 'date-time') {
          type = { text: 'DateTimeOffset', valueType: true }
        } else if (schema.format === 'uri') {
          type = { text: 'Uri', valueType: false }
        } else {
          type = { text: 'string', valueType: false }
        }
        break
      case undefined:
        invariant(CSHARP_JSON_ELEMENT_ALLOWLIST.has(pointer), `Unapproved schemaless C# value at ${pointer}.`)
        type = { text: 'JsonElement', valueType: true }
        break
      default:
        throw new ContractFailure(`Unsupported C# schema type ${schema.type} at ${pointer}.`)
    }
    return allowsNull ? nullable(type) : type
  }

  for (const [name, schema] of Object.entries(componentSchemas)) {
    const rootObjectUnion =
      !schema.type &&
      !schema.properties &&
      ['oneOf', 'anyOf'].some(
        (keyword) =>
          schema[keyword]?.length && schema[keyword].every((candidate) => objectLike(candidate)),
      )
    if (rootObjectUnion) {
      invariant(
        CSHARP_ROOT_JSON_ELEMENT_ALLOWLIST.has(name),
        `Unapproved root object union ${name}; use a converter or add an explicit JsonElement allowlist entry.`,
      )
      continue
    }
    if (!rootEnums.has(name) && objectLike(schema)) {
      reserveClass(name, schema, `#/components/schemas/${name}`)
    }
  }

  function renderClass(entry) {
    const shape = collectShape(entry.schema)
    const lines = [`public sealed class ${entry.name}`, '{']
    for (const [wireName, propertySchema] of [...shape.properties].sort(([left], [right]) =>
      left.localeCompare(right),
    )) {
      const propertyName = csharpIdentifier(wireName)
      const type = csharpType(
        propertySchema,
        `${entry.name}${propertyName}`,
        `${entry.pointer}/properties/${wireName}`,
      )
      lines.push(`    [JsonPropertyName(${JSON.stringify(wireName)})]`)
      if (shape.required.has(wireName)) {
        lines.push(`    public required ${type.text} ${propertyName} { get; init; }`)
      } else {
        lines.push('    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]')
        lines.push(`    public Optional<${type.text}> ${propertyName} { get; init; }`)
      }
      lines.push('')
    }
    if (shape.additionalProperties) {
      lines.push('    [JsonExtensionData]')
      lines.push(
        '    public IDictionary<string, JsonElement>? AdditionalProperties { get; init; }',
        '',
      )
    }
    lines.push('}')
    return lines.join('\n')
  }

  const lines = []
  for (const [name, schema] of Object.entries(componentSchemas)
    .filter(([name]) => rootEnums.has(name))
    .sort(([left], [right]) => left.localeCompare(right))) {
    lines.push('[JsonConverter(typeof(JsonStringEnumConverter))]', `public enum ${name}`, '{')
    for (const member of enumMembers(schema)) {
      lines.push(`    [JsonStringEnumMemberName(${JSON.stringify(member.wireValue)})]`, `    ${member.name},`)
    }
    lines.push('}', '')
  }

  for (let index = 0; index < classQueue.length; index += 1) {
    lines.push(renderClass(classQueue[index]), '')
  }

  return lines.join('\n')
}

export function generateCSharp(openApi, openApiSource, errorCatalogSource) {
  return `${generatedHeader('//', openApiSource, errorCatalogSource)}#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace PoolAI.Contracts.Generated;

[JsonConverter(typeof(OptionalJsonConverterFactory))]
public readonly struct Optional<T>
{
    public Optional(T value)
    {
        HasValue = true;
        Value = value;
    }

    public bool HasValue { get; }

    public T? Value { get; }

    public static implicit operator Optional<T>(T value) => new(value);
}

public sealed class OptionalJsonConverterFactory : JsonConverterFactory
{
    public override bool CanConvert(Type typeToConvert) =>
        typeToConvert.IsGenericType &&
        typeToConvert.GetGenericTypeDefinition() == typeof(Optional<>);

    public override JsonConverter CreateConverter(Type typeToConvert, JsonSerializerOptions options)
    {
        Type valueType = typeToConvert.GetGenericArguments()[0];
        Type converterType = typeof(OptionalJsonConverter<>).MakeGenericType(valueType);
        return (JsonConverter)Activator.CreateInstance(converterType)!;
    }

    private sealed class OptionalJsonConverter<TValue> : JsonConverter<Optional<TValue>>
    {
        public override Optional<TValue> Read(
            ref Utf8JsonReader reader,
            Type typeToConvert,
            JsonSerializerOptions options) =>
            new(JsonSerializer.Deserialize<TValue>(ref reader, options)!);

        public override void Write(
            Utf8JsonWriter writer,
            Optional<TValue> value,
            JsonSerializerOptions options) =>
            JsonSerializer.Serialize(writer, value.Value, options);
    }
}

${csharpGenerator(openApi)}
`
}

function errorCodePropertyName(code) {
  return code
    .split('_')
    .map((part) => `${part[0].toUpperCase()}${part.slice(1)}`)
    .join('')
}

export function generateTypeScriptErrors(catalog, openApiSource, errorCatalogSource) {
  const lines = [
    generatedHeader('//', openApiSource, errorCatalogSource).trimEnd(),
    'export const errorContracts = {',
  ]
  for (const entry of [...catalog.entries].sort((left, right) => left.code.localeCompare(right.code))) {
    lines.push(
      `  ${JSON.stringify(entry.code)}: { status: ${JSON.stringify(entry.status)}, retryable: ${JSON.stringify(entry.retryable)}, retryAfter: ${JSON.stringify(entry.retryAfter)} },`,
    )
  }
  lines.push(
    '} as const',
    '',
    'export type ErrorCode = keyof typeof errorContracts',
    'export const errorCodes = Object.freeze(Object.keys(errorContracts) as ErrorCode[])',
    '',
  )
  return `${lines.join('\n')}\n`
}

export function generateCSharpErrors(catalog, openApiSource, errorCatalogSource) {
  const lines = [
    generatedHeader('//', openApiSource, errorCatalogSource).trimEnd(),
    '#nullable enable',
    '',
    'namespace PoolAI.Contracts.Generated;',
    '',
    'public static class ErrorCodesV1',
    '{',
  ]
  for (const entry of [...catalog.entries].sort((left, right) => left.code.localeCompare(right.code))) {
    lines.push(`    public const string ${errorCodePropertyName(entry.code)} = ${JSON.stringify(entry.code)};`)
  }
  lines.push('}', '')
  return `${lines.join('\n')}\n`
}

async function assertGeneratedFile(file, expected) {
  let actual
  try {
    actual = await readFile(file, 'utf8')
  } catch (error) {
    if (error.code === 'ENOENT') {
      throw new ContractFailure(`Generated file is missing: ${path.relative(process.cwd(), file)}`)
    }
    throw error
  }
  invariant(
    actual === expected,
    `Generated file is stale: ${path.relative(process.cwd(), file)}. Run pnpm --dir frontend contracts:generate.`,
  )
}

export async function generateContracts({
  catalog,
  check,
  errorCatalogSource,
  openApi,
  openApiSource,
}) {
  const outputs = new Map([
    [contractPaths.generatedTypeScript, generateTypeScript(openApi, openApiSource, errorCatalogSource)],
    [
      contractPaths.generatedTypeScriptErrors,
      generateTypeScriptErrors(catalog, openApiSource, errorCatalogSource),
    ],
    [contractPaths.generatedCSharp, generateCSharp(openApi, openApiSource, errorCatalogSource)],
    [
      contractPaths.generatedCSharpErrors,
      generateCSharpErrors(catalog, openApiSource, errorCatalogSource),
    ],
  ])

  for (const [file, content] of outputs) {
    if (check) {
      await assertGeneratedFile(file, content)
    } else {
      await mkdir(path.dirname(file), { recursive: true })
      await writeFile(file, content, 'utf8')
    }
  }
  return [...outputs.keys()]
}
